export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR";
export const RESET_CONSTRUCTOR_SUCCESS = "RESET_CONSTRUCTOR_SUCCESS";
